// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfjbwdjwxaxampqdrfze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmamJ3ZGp3eGF4YW1wcWRyZnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNTc2NjIsImV4cCI6MjA1NjgzMzY2Mn0.3DTi_jciAaPr5P1F1xQ72iqgm29kBEziU679wVaAfwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);